### ISSUE TITLE
java.lang.NoSuchFieldError: VERSION_2_3_30

### ISSUE THREAD

**Issue by RocketTH** [pingfangushi/screw#2]
引入依赖，执行示例代码报错
java.lang.NoSuchFieldError: VERSION_2_3_30
原因是Freemarker版本不对，但是你们源码是这个版本，引入的不是这个版本
![image](https://user-images.githubusercontent.com/14861287/85940250-e7c09600-b94d-11ea-92fb-0d3986ccb815.png)
这样做即可

`
<dependency>
            <groupId>cn.smallbun.screw</groupId>
            <artifactId>screw-core</artifactId>
            <version>1.0.1</version>
            <exclusions>
                <exclusion>
                    <artifactId>freemarker</artifactId>
                    <groupId>org.freemarker</groupId>
                </exclusion>
            </exclusions>
        </dependency>
<dependency>
            <groupId>org.freemarker</groupId>
            <artifactId>freemarker</artifactId>
            <version>2.3.30</version>
        </dependency>
`

**Comment by RocketTH** [comment]
```
<dependency>
            <groupId>cn.smallbun.screw</groupId>
            <artifactId>screw-core</artifactId>
            <version>1.0.1</version>
            <exclusions>
                <exclusion>
                    <artifactId>freemarker</artifactId>
                    <groupId>org.freemarker</groupId>
                </exclusion>
            </exclusions>
        </dependency>


        <!-- https://mvnrepository.com/artifact/org.freemarker/freemarker -->
        <dependency>
            <groupId>org.freemarker</groupId>
            <artifactId>freemarker</artifactId>
            <version>2.3.30</version>
        </dependency>
```

**Comment by RocketTH** [comment]
你们源码中依赖的是2.3.28版本
![image](https://user-images.githubusercontent.com/14861287/85940323-32421280-b94e-11ea-9abc-dbc7866e8c71.png)

**Comment by pingfangushi** [comment]
是不是存在缓存问题，这边源码是2.3.30，确实没有发现这个问题。
